# Generated by Django 5.2.5 on 2025-08-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название баннера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('type_of_bunner', models.CharField(choices=[('index_head', 'head banner on index page'), ('index_middle', 'middle banner on index page'), ('catalog_head', 'head banner on catalog page'), ('brand_head', 'head banner on brand page')], verbose_name='Тип баннера')),
                ('description', models.TextField(verbose_name='Описание баннера')),
                ('cover_image', models.ImageField(upload_to='promotion/', verbose_name='Обложка баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/', verbose_name='Изображения баннера')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotion.banner', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Изображение баннера',
                'verbose_name_plural': 'Изображения баннера',
            },
        ),
    ]
