# Generated by Django 5.2.5 on 2025-08-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='Цвет телефона')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.frame', verbose_name='Корпус')),
                ('memory_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.memorysize', verbose_name='Объем памяти')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.phone', verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефон в наличии',
                'verbose_name_plural': 'Телефоны в наличии',
            },
        ),
    ]
