# Generated by Django 5.2.5 on 2025-08-14 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем батареи')),
                ('type', models.CharField(max_length=50, verbose_name='Тип батареи')),
                ('fast_charging', models.BooleanField(default=True, verbose_name='Быстрая зарядка')),
                ('wireless_charging', models.BooleanField(default=False, verbose_name='Беспроводная зарядка')),
                ('removable', models.BooleanField(default=False, verbose_name='Возможность снятия')),
            ],
            options={
                'verbose_name': 'Батарея',
                'verbose_name_plural': 'Батареи',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название бренда')),
                ('logo', models.ImageField(upload_to='brand_logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип камеры')),
                ('resolution', models.CharField(max_length=50, verbose_name='Разрешение камеры')),
                ('features', models.CharField(max_length=100, verbose_name='Особенности камеры')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Страна производства',
                'verbose_name_plural': 'Страны производства',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_size', models.CharField(max_length=50, verbose_name='Размер экрана')),
                ('display_type', models.CharField(max_length=50, verbose_name='Тип экрана')),
                ('refresh_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Частота обновления')),
            ],
            options={
                'verbose_name': 'Дисплей',
                'verbose_name_plural': 'Дисплеи',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_material', models.CharField(max_length=255, verbose_name='Материал корпуса')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='MemorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Объем памяти')),
            ],
            options={
                'verbose_name': 'Объем памяти',
                'verbose_name_plural': 'Объемы памяти',
            },
        ),
        migrations.CreateModel(
            name='CameraModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер модуля')),
                ('resolution', models.CharField(max_length=50, verbose_name='Разрешение модуля')),
                ('features', models.CharField(max_length=100, verbose_name='Особенности модуля')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Модуль камеры',
                'verbose_name_plural': 'Модули камер',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель телефона')),
                ('phone_version', models.CharField(choices=[('SL', 'Slim'), ('PR', 'Pro'), ('ST', 'Standard'), ('UL', 'Ultra'), ('PM', 'Pro Max'), ('Pl', 'Plus')], verbose_name='Версия телефона')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Цена телефона')),
                ('description', models.TextField(verbose_name='Описание телефона')),
                ('oc_version', models.CharField(max_length=50, verbose_name='Версия ОС')),
                ('cover_photo', models.ImageField(upload_to='cover_photos/', verbose_name='Главная фотография')),
                ('phone_cpu', models.CharField(max_length=50, verbose_name='Процессор телефона')),
                ('cpu_cores', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ядер процессора')),
                ('cpu_frequency', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Частота процессора')),
                ('ram', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ОЗУ')),
                ('network', models.CharField(max_length=50, verbose_name='Сеть')),
                ('wifi_standart', models.CharField(max_length=50, verbose_name='Стандарт WiFi')),
                ('bluetooth_standart', models.CharField(max_length=50, verbose_name='Стандарт Bluetooth')),
                ('nfs_support', models.BooleanField(default=True, verbose_name='Поддержка NFS')),
                ('release_year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.battery', verbose_name='Батарея')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand', verbose_name='Бренд')),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.countryoforigin', verbose_name='Страна производства')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.display', verbose_name='Дисплей')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.phone', verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone_images/', verbose_name='Фотографии телефона')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.phone', verbose_name='Фотографии телефона')),
            ],
            options={
                'verbose_name': 'Фотографии телефона',
                'verbose_name_plural': 'Фотографии телефонов',
            },
        ),
    ]
